name: Build Latex Project
on: push
jobs:
  pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y python3
      - run: pip install pygments
      - uses: actions-rs/toolchain@v1
      - run: cargo install tectonic
      - run: bash run.sh
      - uses: actions/upload-artifact@v2
        with:
          name: rendered-pdf
          path: main.pdf
          retention-days: 7
