name: Build Latex Project
on: push
jobs:
  pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3
      - run: pip install pygments
      - run: sudo apt-get install libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: tectonic
      - uses: actions/checkout@v2
      - run: bash run.sh
      - uses: actions/upload-artifact@v2
        with:
          name: rendered-pdf
          path: main.pdf
          retention-days: 7
